import hashidoImage from "./assets/restaurants/hashido.jpg";
import brisketImage from "./assets/restaurants/brisket-rony.jpg";
import chochinImage from "./assets/restaurants/chochin.jpg";
import nikusyukaImage from "./assets/restaurants/nikusyuka-3610.jpg";
import sakabukuroImage from "./assets/restaurants/sakabukuro.jpg";
import sumiginImage from "./assets/restaurants/sumigin.jpg";

export const restaurants = [
  {
    id: "hashido",
    name: "焼肉・ホルモン はしど",
    shortName: "焼肉はしど",
    category: "焼肉",
    filterCategory: "焼肉",
    address: "京都市中京区中之町565-23 ハレの日花遊小路 1F",
    instagram: "https://www.instagram.com/yakiniku_hashido/",
    heroImage: hashidoImage,
    headline: "うまいロースと、うまいタレ。",
    summary: "花遊小路で楽しむ、タレ推しの大衆街焼肉。カウンター席もあり、ひとり焼肉から仲間との夜まで気軽に立ち寄れる一軒です。",
    story: [
      "京都河原町の花遊小路に店を構える、タレを主役にした大衆焼肉店です。上質なロースや希少部位、ホルモンを、肉の持ち味を引き立てる自慢のタレで味わえます。",
      "カウンター席でのひとり焼肉から、友人との食事、夜遅めの一軒まで。気取らず焼肉を囲める街の店として、京都の夜に寄り添います。",
    ],
    hours: "17:00〜翌2:00（最新情報はInstagramで確認）",
    holiday: "第2・第3水曜（変更あり）",
    access: "京都河原町・花遊小路内。詳しい経路はGoogleマップでご確認ください。",
    reservation: "予約・空席状況は電話（075-231-1774）またはInstagramでご確認ください。",
    seating: "カウンター席があり、おひとりでの利用にも向いています。",
    groupUse: "グループ利用や人数の相談は、来店前に店舗へご確認ください。",
    menuHighlights: [
      { name: "焼肉・ロース（タレ）", label: "店の流儀", body: "サシの入ったロースを、自慢のタレで。ごはんにもお酒にも合う看板メニューです。" },
      { name: "サガリ", label: "希少部位", body: "あっさりとしたコクとやわらかな肉質。塩またはタレで楽しめます。" },
      { name: "秘伝のタレで作るチゲスープ", label: "締めの一杯", body: "鶏ガラ出汁と焼肉のモミダレを合わせた、体が温まる締めのスープです。" },
    ],
    occasions: [
      { title: "ひとり焼肉に", body: "カウンターで、自分のペースで好きな部位を。" },
      { title: "友人との食事に", body: "ロースやホルモンを囲み、気取らない夜を。" },
      { title: "遅めの一軒に", body: "夜遅くの食事にも。営業状況は当日ご確認ください。" },
    ],
    source: { label: "店舗公開メニューページ", url: "https://bakabonhadime.com/menu.html" },
    features: [
      { title: "タレが主役", body: "肉の旨みを引き立てる、はしど自慢のタレ。大衆焼肉らしい気取らないおいしさを。" },
      { title: "街の焼肉", body: "京都河原町・花遊小路の路地で、仕事帰りや夜の二軒目にも立ち寄れる焼肉店です。" },
      { title: "ひとりでも", body: "カウンター席があり、おひとりさまの焼肉にも。最新の営業案内はInstagramで確認できます。" },
    ],
    glyph: "焼",
    accent: "#9f2f20",
  },
  {
    id: "brisket-rony",
    name: "Brisket RONY",
    shortName: "Brisket RONY",
    category: "韓国料理・焼肉",
    filterCategory: "韓国料理",
    address: "京都市中京区小結棚町434-4",
    instagram: "https://www.instagram.com/brisketrony/",
    heroImage: brisketImage,
    headline: "京都で出会う、韓流焼肉チャドルバギ。",
    summary: "黒毛和牛のブリスケを薄くスライスし、野菜を巻いて味わう韓流焼肉。初めての方にもスタッフが食べ方を案内しています。",
    story: [
      "黒毛和牛のブリスケを極薄にスライスし、鉄板でさっと焼く韓国スタイルの焼肉「チャドルバギ」を楽しめる専門店です。",
      "焼いた肉は野菜や薬味、特製の甘酸っぱいタレと一緒に。重たくなりすぎない食べ方と、スタッフによる案内で、初めての方にも選びやすい一軒です。",
    ],
    hours: "17:30〜24:00",
    holiday: "不定休／最新情報はInstagramへ",
    access: "地下鉄四条駅・阪急烏丸駅から新町通方面へ。詳しい経路はGoogleマップでご確認ください。",
    reservation: "公開グルメサイトではネット予約を受け付けています。最新の空席状況をご確認ください。",
    seating: "ひとりからグループまで利用可能。席種や人数は予約時にご確認ください。",
    groupUse: "飲み放題付きプランの公開情報があります。内容・受付条件は予約時にご確認ください。",
    menuHighlights: [
      { name: "黒毛和牛チャドルバギ", label: "看板料理", body: "極薄のブリスケを鉄板でさっと焼き、野菜や薬味と味わう韓流焼肉です。" },
      { name: "黒毛和牛ブリスケ料理", label: "専門店の一皿", body: "前足の付け根付近にあるブリスケの旨みを生かした肉料理です。" },
      { name: "コース・飲み放題", label: "集まりにも", body: "チャドルバギと一品料理を組み合わせたプランが公開されています。" },
    ],
    occasions: [
      { title: "初めての韓国焼肉に", body: "おすすめの焼き方や食べ方を案内してもらえます。" },
      { title: "友人との集まりに", body: "鉄板を囲みながら、会話と食事を楽しめます。" },
      { title: "宴会・会食に", body: "コースや飲み放題の内容を事前に相談できます。" },
    ],
    source: { label: "店舗公開情報（食べログ）", url: "https://tabelog.com/kyoto/A2601/A260201/26032844/" },
    features: [
      { title: "チャドルバギ", body: "黒毛和牛のブリスケを薄くスライス。鉄板でさっと焼き上げる韓国発祥の焼肉です。" },
      { title: "野菜を巻いて", body: "新鮮な野菜や薬味と一緒に味わう、軽やかな食べ方もチャドルバギの魅力です。" },
      { title: "初めてでも安心", body: "スタッフが焼き方やおすすめの食べ方をご案内。韓流焼肉が初めての方にも。" },
    ],
    glyph: "包",
    accent: "#781823",
  },
  {
    id: "chochin",
    name: "提灯食堂",
    shortName: "提灯食堂",
    category: "居酒屋",
    filterCategory: "居酒屋",
    address: "京都市中京区壬生西檜町11-3 壬生店舗2号",
    instagram: "https://www.instagram.com/chochin0928/",
    heroImage: chochinImage,
    headline: "夜更けまで灯る、街の居酒屋。",
    summary: "西院南部エリアで18時から深夜2時まで。提灯の灯りを目印に、気取らない夜の時間を楽しめる地域の居酒屋です。",
    story: [
      "西院駅から歩ける壬生西檜町にある、昭和の大衆酒場を思わせる居酒屋です。提灯の灯りと親しみのある空間で、料理とお酒を気軽に楽しめます。",
      "遅い時間の食事、仕事帰りの一杯、友人や家族との食事まで幅広い利用シーンに。営業日の変更やその日の案内はInstagramで発信されています。",
    ],
    hours: "18:00〜翌2:00",
    holiday: "基本水曜／営業する水曜あり",
    access: "西院駅から徒歩圏内。壬生西檜町の店舗で、詳しい経路はGoogleマップをご利用ください。",
    reservation: "公開グルメサイトではネット予約案内があります。最新の受付状況をご確認ください。",
    seating: "テーブル席を中心とした大衆酒場。ひとり利用の可否は混雑状況を含め店舗へご確認ください。",
    groupUse: "食事会や小規模な集まりの相談は、事前に店舗へお問い合わせください。",
    menuHighlights: [
      { name: "日替わりの酒肴", label: "その日の一皿", body: "当日のおすすめや提供内容は、店内案内やInstagramで確認できます。" },
      { name: "大衆酒場の一品", label: "気軽な食事", body: "お酒と合わせやすい居酒屋料理を、気取らない雰囲気で楽しめます。" },
      { name: "豊富なドリンク", label: "夜の一杯", body: "料理や気分に合わせて選ぶ一杯。最新の品揃えは店舗でご確認ください。" },
    ],
    occasions: [
      { title: "仕事帰りに", body: "提灯を目印に、食事と一杯を気軽に。" },
      { title: "友人や家族と", body: "テーブルを囲んで楽しめる大衆居酒屋です。" },
      { title: "遅い時間の食事に", body: "深夜帯の利用前には当日の営業状況をご確認ください。" },
    ],
    source: { label: "店舗公開情報（食べログ）", url: "https://tabelog.com/kyoto/A2601/A260401/26026248/" },
    features: [
      { title: "提灯の灯り", body: "夜の街に灯る提灯が目印。仕事帰りにも立ち寄りやすい、親しみのある佇まいです。" },
      { title: "深夜2時まで", body: "18時に開店し、深夜2時まで営業。遅い時間の食事や一杯にも寄り添います。" },
      { title: "西院南部", body: "壬生西檜町の地域に根ざした居酒屋。営業日の変更はInstagramで案内されています。" },
    ],
    glyph: "灯",
    accent: "#b33822",
  },
  {
    id: "nikusyuka-3610",
    name: "肉酒家3610",
    shortName: "肉酒家3610",
    category: "居酒屋・肉料理",
    filterCategory: "居酒屋",
    address: "京都市中京区壬生森前町5 山田ビル1F",
    instagram: "https://www.instagram.com/nikusyuka3610/",
    heroImage: nikusyukaImage,
    headline: "肉と酒が、夜をほどく。",
    summary: "西院エリアの肉料理を中心にした居酒屋。ローストビーフ丼など、しっかり食べたい日の一軒に。",
    story: [
      "壬生森前町で、肉を主役にした料理とお酒を楽しめる居酒屋です。食事として満足できる丼や弁当の公開情報もあり、しっかり食べたい日の選択肢になります。",
      "店内での過ごし方、テイクアウトやランチの最新状況は変わることがあるため、来店前にInstagramで確認するのがおすすめです。",
    ],
    hours: "最新情報はInstagramで確認",
    holiday: "営業日はInstagramで確認",
    access: "西院エリア・壬生森前町。詳しい経路はGoogleマップでご確認ください。",
    reservation: "予約方法や空席状況はInstagramから店舗へご確認ください。",
    seating: "席種・ひとり利用・混雑状況は、来店前に店舗へご確認ください。",
    groupUse: "複数名での利用や料理の相談は、事前に店舗へお問い合わせください。",
    menuHighlights: [
      { name: "ローストビーフ丼", label: "公開情報掲載", body: "肉をしっかり味わえる丼として公開グルメ情報で紹介されている一品です。" },
      { name: "和牛焼き肉弁当", label: "テイクアウト情報", body: "和牛を特製タレで焼き上げた弁当として、公開デリバリー情報に掲載されています。" },
      { name: "鶏からのっけ丼", label: "ボリューム飯", body: "下味をつけた鶏もも肉の唐揚げをのせた丼として公開されています。" },
    ],
    occasions: [
      { title: "肉をしっかり食べたい日に", body: "丼や肉料理を中心に満足感のある食事を。" },
      { title: "仕事帰りに", body: "西院・壬生エリアで肉料理とお酒を楽しめます。" },
      { title: "持ち帰りを検討するとき", body: "受付状況や対象メニューを事前にご確認ください。" },
    ],
    source: { label: "公開メニュー情報（Uber Eats）", url: "https://www.ubereats.com/jp/store/%E8%82%89%E9%85%92%E5%AE%B63610/UlkLclcBWoS17qsYi5XT2A" },
    features: [
      { title: "肉料理", body: "店名のとおり、肉を主役にした料理を楽しめる居酒屋。食事にも酒席にも似合います。" },
      { title: "ローストビーフ丼", body: "公開情報でも紹介される肉の丼。しっかり食べたい日に選びたい一品です。" },
      { title: "西院の夜", body: "壬生森前町の路地で、街の日常に寄り添う一軒。最新情報はInstagramで確認できます。" },
    ],
    glyph: "肉",
    accent: "#a64e24",
  },
  {
    id: "sakabukuro",
    name: "さかぶくろ",
    shortName: "さかぶくろ",
    category: "居酒屋・海鮮",
    filterCategory: "居酒屋",
    address: "京都市中京区壬生仙念町10-5 B1F",
    instagram: "https://www.instagram.com/sakabukuro/",
    heroImage: sakabukuroImage,
    headline: "旬の魚と、日本酒を。",
    summary: "京都市中央市場の仲卸が薦める、季節の魚を味わう居酒屋。お造り盛り合わせや日替わりの酒肴を楽しめます。",
    story: [
      "京都市中央市場から仕入れる魚介や野菜を使い、旬の味を日本酒に合う一皿へ仕立てる居酒屋です。長年の仲卸業者とのつながりを生かした素材選びが魅力です。",
      "カウンターでのひとり飲みから座敷での宴会まで。平日の昼には魚介を使った日替わり定食も紹介されており、昼夜それぞれの楽しみ方があります。",
    ],
    hours: "平日ランチ11:00〜14:00／夜17:00〜23:00（金・土・祝前日は24:00まで）",
    holiday: "日曜（最新情報はInstagramで確認）",
    access: "阪急・嵐電 西院駅から徒歩約2分。地下1階の店舗です。",
    reservation: "京都市中央市場の紹介ページでは予約可能と案内されています。最新状況をご確認ください。",
    seating: "カウンターと座敷があり、ひとり飲みから複数名まで利用できます。",
    groupUse: "宴会利用も可能と紹介されています。人数・料理内容は事前に店舗へご相談ください。",
    menuHighlights: [
      { name: "お造り盛り合わせ", label: "常連の定番", body: "鮮度の良い魚介を、その日の内容で盛り合わせる店の中心的な一皿です。" },
      { name: "日替わりの魚介料理", label: "旬の酒肴", body: "昆布締めや塩たたきなど、季節の素材を日本酒に合う形で提供します。" },
      { name: "魚介の日替わり定食", label: "平日ランチ", body: "昼は魚介を主役にした日替わり定食が紹介されています。" },
    ],
    occasions: [
      { title: "ひとり飲みに", body: "カウンターで旬の魚と日本酒をゆっくりと。" },
      { title: "魚好きの友人と", body: "お造りや日替わりの酒肴を分け合えます。" },
      { title: "宴会・集まりに", body: "座敷利用の人数や料理を事前に相談できます。" },
    ],
    source: { label: "京都市中央市場 推薦店ページ", url: "https://shun.kyoto-ichiba.jp/restaurant/170/" },
    features: [
      { title: "旬のお造り", body: "常連客にも親しまれるお造り盛り合わせ。季節ごとに変わる魚の表情を味わえます。" },
      { title: "日替わりの酒肴", body: "昆布締めや塩たたきなど、その日の素材を日本酒に合う一皿へ仕立てます。" },
      { title: "市場の推薦店", body: "京都市中央市場の仲卸業者が薦める店として紹介される、魚好きのための一軒です。" },
    ],
    glyph: "旬",
    accent: "#31566a",
  },
  {
    id: "sumigin",
    name: "炭吟醸",
    shortName: "炭吟醸",
    category: "居酒屋・炭火料理",
    filterCategory: "居酒屋",
    address: "京都市中京区壬生馬場町15-17",
    instagram: "https://www.instagram.com/sumigin2020/",
    heroImage: sumiginImage,
    headline: "昼はラーメン、夜は炭火焼き。",
    summary: "二条駅からほど近い、昼夜で表情を変える居酒屋。昼のラーメンから、夜の鶏の炭火焼きと日本酒まで。",
    story: [
      "三条会商店街の近くで、昼はラーメン、夜は炭火居酒屋として営業する一軒です。夜は串に刺さない宮崎風の鶏の籠焼きを中心に、部位ごとの味わいを楽しめます。",
      "カウンター、小上がり、個室の紹介があり、ひとりの食事からグループまで。炭火の香りに合わせる日本酒や一品料理も揃います。",
    ],
    hours: "11:00〜14:00 / 17:00〜24:00",
    holiday: "月曜夜休みの案内あり／最新情報はInstagramで確認",
    access: "二条駅・三条会商店街西側から徒歩圏内。詳しい経路はGoogleマップをご利用ください。",
    reservation: "公開記事では予約利用が紹介されています。最新の空席状況は店舗へご確認ください。",
    seating: "カウンター、小上がり、個室の公開情報があります。席の指定は予約時にご確認ください。",
    groupUse: "複数名や個室利用は事前予約がおすすめです。人数条件は店舗へご確認ください。",
    menuHighlights: [
      { name: "鶏ももの籠焼き", label: "夜の看板", body: "串に刺さず炭火で香ばしく焼く宮崎風の鶏料理。塩・タレで楽しめます。" },
      { name: "濃厚鶏白湯ラーメン", label: "昼の一杯", body: "ランチタイムに提供情報がある、鶏の旨みを生かした濃厚なラーメンです。" },
      { name: "日本酒と一品料理", label: "酒の時間", body: "炭火焼きに合わせる日本酒や、ポテトサラダなどの一品料理が紹介されています。" },
    ],
    occasions: [
      { title: "昼のラーメンに", body: "ランチ営業と当日の提供状況をご確認ください。" },
      { title: "日本酒と炭火料理に", body: "部位ごとの籠焼きと一杯をゆっくりと。" },
      { title: "グループの食事に", body: "小上がりや個室の利用条件を事前に相談できます。" },
    ],
    source: { label: "キョウトピ掲載記事", url: "https://kyotopi.jp/articles/ZTb0V" },
    features: [
      { title: "昼のラーメン", body: "昼はラーメンを提供。中京区でのランチに、しっかり温まる一杯を。" },
      { title: "夜の炭火焼き", body: "夜は炭火焼き居酒屋へ。鶏を炭火で香ばしく焼き上げる料理が看板です。" },
      { title: "日本酒とともに", body: "炭火の香りに合う日本酒と、仕事帰りの一杯を。最新メニューはInstagramへ。" },
    ],
    glyph: "炭",
    accent: "#9a3e1d",
  },
];

export const researchProspects = [
  {
    id: "cut-house-kingyo",
    name: "cut house kingyo",
    category: "美容院",
    filterCategory: "美容・理容",
    address: "京都市中京区三条通黒門西入御供町280",
    websiteStatus: "HPなし確認済み",
    stage: "提案準備",
    priority: "高",
    nextAction: "公開情報を整理",
    timing: "今日",
    sourceLabel: "京都市 宣言店舗一覧",
    sourceUrl: "https://www.city.kyoto.lg.jp/hokenfukushi/page/0000127820.html",
  },
  {
    id: "honu-salon",
    name: "honu",
    category: "美容院",
    filterCategory: "美容・理容",
    address: "京都市中京区三条通大宮東入御供町284",
    websiteStatus: "HPなし確認済み",
    stage: "提案準備",
    priority: "高",
    nextAction: "提案ページの構成作成",
    timing: "今日",
    sourceLabel: "京都市 宣言店舗一覧",
    sourceUrl: "https://www.city.kyoto.lg.jp/hokenfukushi/page/0000127820.html",
  },
  {
    id: "arakimusen",
    name: "アラキムセン",
    category: "地域電器店",
    filterCategory: "生活サービス",
    address: "京都市中京区西ノ京内畑町23",
    websiteStatus: "HP確認待ち",
    stage: "HP確認待ち",
    priority: "中",
    nextAction: "GoogleマップでHP確認",
    timing: "今週",
    sourceLabel: "京都省エネ家電購入キャンペーン登録店舗",
    sourceUrl: "https://kyoto-shoene.jp/files/index_shoplist.pdf?ver=20260114",
  },
  {
    id: "ace-denka-center",
    name: "エース電化センター",
    category: "地域電器店",
    filterCategory: "生活サービス",
    address: "京都市中京区西ノ京冷泉町136-1",
    websiteStatus: "HP確認待ち",
    stage: "HP確認待ち",
    priority: "中",
    nextAction: "GoogleマップでHP確認",
    timing: "今週",
    sourceLabel: "京都省エネ家電購入キャンペーン登録店舗",
    sourceUrl: "https://kyoto-shoene.jp/files/index_shoplist.pdf?ver=20260114",
  },
  {
    id: "okita-denki",
    name: "尾北電気商会",
    category: "地域電器店",
    filterCategory: "生活サービス",
    address: "京都市中京区壬生松原町54",
    websiteStatus: "HP確認待ち",
    stage: "HP確認待ち",
    priority: "中",
    nextAction: "GoogleマップでHP確認",
    timing: "今週",
    sourceLabel: "京都省エネ家電購入キャンペーン登録店舗",
    sourceUrl: "https://kyoto-shoene.jp/files/index_shoplist.pdf?ver=20260114",
  },
  {
    id: "onkyo-denkasha",
    name: "音響電化社",
    category: "地域電器店",
    filterCategory: "生活サービス",
    address: "京都市中京区蛸薬師通高倉東入ル雁金町369",
    websiteStatus: "HP確認待ち",
    stage: "HP確認待ち",
    priority: "中",
    nextAction: "GoogleマップでHP確認",
    timing: "今週",
    sourceLabel: "京都省エネ家電購入キャンペーン登録店舗",
    sourceUrl: "https://kyoto-shoene.jp/files/index_shoplist.pdf?ver=20260114",
  },
  {
    id: "katsuya-denki",
    name: "かつや電気商会",
    category: "地域電器店",
    filterCategory: "生活サービス",
    address: "京都市中京区壬生土居ノ内町41-14",
    websiteStatus: "HP確認待ち",
    stage: "HP確認待ち",
    priority: "中",
    nextAction: "GoogleマップでHP確認",
    timing: "今週",
    sourceLabel: "京都省エネ家電購入キャンペーン登録店舗",
    sourceUrl: "https://kyoto-shoene.jp/files/index_shoplist.pdf?ver=20260114",
  },
  {
    id: "kaneda-denki",
    name: "兼田電機商会",
    category: "地域電器店",
    filterCategory: "生活サービス",
    address: "京都市中京区壬生朱雀町2",
    websiteStatus: "HP確認待ち",
    stage: "HP確認待ち",
    priority: "中",
    nextAction: "GoogleマップでHP確認",
    timing: "今週",
    sourceLabel: "京都省エネ家電購入キャンペーン登録店舗",
    sourceUrl: "https://kyoto-shoene.jp/files/index_shoplist.pdf?ver=20260114",
  },
  {
    id: "koizumi-denki",
    name: "小泉電気",
    category: "地域電器店",
    filterCategory: "生活サービス",
    address: "京都市中京区西ノ京右馬寮町8-34",
    websiteStatus: "HP確認待ち",
    stage: "HP確認待ち",
    priority: "中",
    nextAction: "GoogleマップでHP確認",
    timing: "今週",
    sourceLabel: "京都省エネ家電購入キャンペーン登録店舗",
    sourceUrl: "https://kyoto-shoene.jp/files/index_shoplist.pdf?ver=20260114",
  },
  {
    id: "salad-denki",
    name: "サラダ電気",
    category: "地域電器店",
    filterCategory: "生活サービス",
    address: "京都市中京区西ノ京藤ノ木町1",
    websiteStatus: "HP確認待ち",
    stage: "HP確認待ち",
    priority: "中",
    nextAction: "GoogleマップでHP確認",
    timing: "今週",
    sourceLabel: "京都省エネ家電購入キャンペーン登録店舗",
    sourceUrl: "https://kyoto-shoene.jp/files/index_shoplist.pdf?ver=20260114",
  },
  {
    id: "tada-shoten",
    name: "多田商店",
    category: "地域電器店",
    filterCategory: "生活サービス",
    address: "京都市中京区壬生高樋町60",
    websiteStatus: "HP確認待ち",
    stage: "HP確認待ち",
    priority: "中",
    nextAction: "GoogleマップでHP確認",
    timing: "今週",
    sourceLabel: "京都省エネ家電購入キャンペーン登録店舗",
    sourceUrl: "https://kyoto-shoene.jp/files/index_shoplist.pdf?ver=20260114",
  },
  {
    id: "tanaka-denki",
    name: "田中電器",
    category: "地域電器店",
    filterCategory: "生活サービス",
    address: "京都市中京区西ノ京内畑町24",
    websiteStatus: "HP確認待ち",
    stage: "HP確認待ち",
    priority: "中",
    nextAction: "GoogleマップでHP確認",
    timing: "今週",
    sourceLabel: "京都省エネ家電購入キャンペーン登録店舗",
    sourceUrl: "https://kyoto-shoene.jp/files/index_shoplist.pdf?ver=20260114",
  },
  {
    id: "nakajima-denki",
    name: "中島電機",
    category: "地域電器店",
    filterCategory: "生活サービス",
    address: "京都市中京区大文字町 黒門通御池下る245-2",
    websiteStatus: "HP確認待ち",
    stage: "HP確認待ち",
    priority: "中",
    nextAction: "GoogleマップでHP確認",
    timing: "今週",
    sourceLabel: "京都省エネ家電購入キャンペーン登録店舗",
    sourceUrl: "https://kyoto-shoene.jp/files/index_shoplist.pdf?ver=20260114",
  },
  {
    id: "fujimoto-denka",
    name: "フジモト電化",
    category: "地域電器店",
    filterCategory: "生活サービス",
    address: "京都市中京区西ノ京南上合町82-27",
    websiteStatus: "HP確認待ち",
    stage: "HP確認待ち",
    priority: "中",
    nextAction: "GoogleマップでHP確認",
    timing: "今週",
    sourceLabel: "京都省エネ家電購入キャンペーン登録店舗",
    sourceUrl: "https://kyoto-shoene.jp/files/index_shoplist.pdf?ver=20260114",
  },
  {
    id: "yasuda-nenju",
    name: "株式会社 安田念珠店",
    category: "念珠・薫香",
    filterCategory: "小売・専門店",
    address: "京都市中京区 寺町京極商店街（番地要確認）",
    websiteStatus: "HP確認待ち",
    stage: "HP確認待ち",
    priority: "中",
    nextAction: "住所と公式サイトを確認",
    timing: "今週",
    sourceLabel: "寺町京極商店街 ショップ一覧",
    sourceUrl: "https://www.kyoto-teramachi.or.jp/shop/",
  },
  {
    id: "hirai-hamono",
    name: "包丁屋刃物屋 平囲",
    category: "包丁・刃物",
    filterCategory: "小売・専門店",
    address: "京都市中京区 寺町京極商店街（番地要確認）",
    websiteStatus: "HP確認待ち",
    stage: "HP確認待ち",
    priority: "中",
    nextAction: "住所と公式サイトを確認",
    timing: "今週",
    sourceLabel: "寺町京極商店街 ショップ一覧",
    sourceUrl: "https://www.kyoto-teramachi.or.jp/shop/",
  },
  {
    id: "binozen-teramachi",
    name: "美の膳 寺町店",
    category: "京みやげ・生活雑貨",
    filterCategory: "小売・専門店",
    address: "京都市中京区 寺町京極商店街（番地要確認）",
    websiteStatus: "HP確認待ち",
    stage: "HP確認待ち",
    priority: "中",
    nextAction: "住所と公式サイトを確認",
    timing: "今週",
    sourceLabel: "寺町京極商店街 ショップ一覧",
    sourceUrl: "https://www.kyoto-teramachi.or.jp/shop/",
  },
  {
    id: "marumi-real-estate",
    name: "丸美不動産株式会社",
    category: "不動産",
    filterCategory: "専門サービス",
    address: "京都市中京区 寺町京極商店街（番地要確認）",
    websiteStatus: "HP確認待ち",
    stage: "HP確認待ち",
    priority: "中",
    nextAction: "住所と公式サイトを確認",
    timing: "今週",
    sourceLabel: "寺町京極商店街 ショップ一覧",
    sourceUrl: "https://www.kyoto-teramachi.or.jp/shop/",
  },
  {
    id: "japanime-art-gallery",
    name: "Japanime Art Gallery",
    category: "アートギャラリー",
    filterCategory: "小売・専門店",
    address: "京都市中京区 寺町京極商店街（番地要確認）",
    websiteStatus: "HP確認待ち",
    stage: "HP確認待ち",
    priority: "中",
    nextAction: "住所と公式サイトを確認",
    timing: "今週",
    sourceLabel: "寺町京極商店街 ショップ一覧",
    sourceUrl: "https://www.kyoto-teramachi.or.jp/shop/",
  },
  {
    id: "jabber-vintage",
    name: "古着屋 jaBBer",
    category: "古着",
    filterCategory: "小売・専門店",
    address: "京都市中京区 寺町京極商店街（番地要確認）",
    websiteStatus: "HP確認待ち",
    stage: "HP確認待ち",
    priority: "中",
    nextAction: "住所と公式サイトを確認",
    timing: "今週",
    sourceLabel: "寺町京極商店街 ショップ一覧",
    sourceUrl: "https://www.kyoto-teramachi.or.jp/shop/",
  },
  {
    id: "ruffue",
    name: "RUFFUE",
    category: "革バッグ・革小物",
    filterCategory: "小売・専門店",
    address: "京都市中京区 寺町京極商店街（番地要確認）",
    websiteStatus: "HP確認待ち",
    stage: "HP確認待ち",
    priority: "中",
    nextAction: "住所と公式サイトを確認",
    timing: "今週",
    sourceLabel: "寺町京極商店街 ショップ一覧",
    sourceUrl: "https://www.kyoto-teramachi.or.jp/shop/",
  },
  {
    id: "resh-kyoto",
    name: "RESH 京都店",
    category: "靴修理",
    filterCategory: "生活サービス",
    address: "京都市中京区 寺町京極商店街（番地要確認）",
    websiteStatus: "HP確認待ち",
    stage: "HP確認待ち",
    priority: "中",
    nextAction: "住所と公式サイトを確認",
    timing: "今週",
    sourceLabel: "寺町京極商店街 ショップ一覧",
    sourceUrl: "https://www.kyoto-teramachi.or.jp/shop/",
  },
  {
    id: "ono-nenju",
    name: "有限会社 小野珠数店",
    category: "珠数製造販売",
    filterCategory: "小売・専門店",
    address: "京都市中京区 寺町京極商店街（番地要確認）",
    websiteStatus: "HP確認待ち",
    stage: "HP確認待ち",
    priority: "中",
    nextAction: "住所と公式サイトを確認",
    timing: "今週",
    sourceLabel: "寺町京極商店街 ショップ一覧",
    sourceUrl: "https://www.kyoto-teramachi.or.jp/shop/",
  },
  {
    id: "daishodo",
    name: "大書堂",
    category: "古書・版画",
    filterCategory: "小売・専門店",
    address: "京都市中京区 寺町京極商店街（番地要確認）",
    websiteStatus: "HP確認待ち",
    stage: "HP確認待ち",
    priority: "中",
    nextAction: "住所と公式サイトを確認",
    timing: "今週",
    sourceLabel: "寺町京極商店街 ショップ一覧",
    sourceUrl: "https://www.kyoto-teramachi.or.jp/shop/",
  },
];

export const salesProspects = [
  ...restaurants.map((restaurant) => ({ ...restaurant, filterCategory: "飲食", hasProposal: true })),
  ...researchProspects.map((prospect) => ({ ...prospect, instagram: null, hasProposal: false })),
];

export const categories = ["すべて", "飲食", "美容・理容", "小売・専門店", "健康・ウェルネス", "教室・スクール", "生活サービス", "宿泊・観光", "専門サービス"];

export const getRestaurantById = (id) => restaurants.find((restaurant) => restaurant.id === id);
